<?php
return [
    'sales' => [
        'routes' => [
            'user.dashboard',
            'user.profile',
            'user.profile.image.update',
            'user.profile.update',
            'customer.company.index',
            'customer.contact.index',
            'customer.contact.store',
            'customer.contact.edit',
            'customer.contact.update',
            'team-member.index',
            'brand.index',
            'lead.index',
            'lead.store',
            'lead.edit',
            'lead.update',
            'lead.convert',
            'lead.change.lead-status',
            'lead-status.index',
            'invoice.index',
            'invoice.store',
            'invoice.edit',
            'invoice.update',
            'invoice.payment_proofs',
            'user.client.account.by.brand',
            'user.payment.index',
            'payment-transaction-logs',
            'save.settings',
        ],
        'restrictions' => [
            'user.client.contact.index',
            'user.client.contact.store',
            'user.client.contact.edit',
            'user.client.contact.update',
            'user.client.contact.change.status',
            'user.client.company.index',
            'user.client.company.store',
            'user.client.contact.companies',
            'user.client.company.edit',
            'user.client.company.update',
            'user.client.company.change.status',
            'user.client.account.index',
            'user.client.account.store',
            'user.client.account.edit',
            'user.client.account.update',
            'user.client.account.change.status',
        ]
    ],
    'development' => [
        'routes' => [
        ],
        'restrictions' => [
            'user.client.contact.index',
            'user.client.contact.store',
            'user.client.contact.edit',
            'user.client.contact.update',
            'user.client.contact.change.status',
            'user.client.company.index',
            'user.client.company.store',
            'user.client.contact.companies',
            'user.client.company.edit',
            'user.client.company.update',
            'user.client.company.change.status',
            'user.client.account.index',
            'user.client.account.store',
            'user.client.account.edit',
            'user.client.account.update',
            'user.client.account.change.status',
        ]
    ],
    'marketing' => [
        'routes' => [
            'user.dashboard', // Marketing dashboard
            'user.profile',
            'user.profile.image.update',
            'user.profile.update',
            'save.settings',
        ],
        'restrictions' => [
            'user.client.contact.index',
            'user.client.contact.store',
            'user.client.contact.edit',
            'user.client.contact.update',
            'user.client.contact.change.status',
            'user.client.company.index',
            'user.client.company.store',
            'user.client.contact.companies',
            'user.client.company.edit',
            'user.client.company.update',
            'user.client.company.change.status',
            'user.client.account.index',
            'user.client.account.store',
            'user.client.account.edit',
            'user.client.account.update',
            'user.client.account.change.status',
        ]
    ],
    'humanresources' => [
        'routes' => [
        ],
        'restrictions' => [
            'user.client.contact.index',
            'user.client.contact.store',
            'user.client.contact.edit',
            'user.client.contact.update',
            'user.client.contact.change.status',
            'user.client.company.index',
            'user.client.company.store',
            'user.client.contact.companies',
            'user.client.company.edit',
            'user.client.company.update',
            'user.client.company.change.status',
            'user.client.account.index',
            'user.client.account.store',
            'user.client.account.edit',
            'user.client.account.update',
            'user.client.account.change.status',
        ]
    ],
    'operations' => [
        'restrictions' => [
        ],
        'roles' => [
            'Q/A Analyst' => [
                'routes' => [
                    'user.dashboard',
                    'save.settings',
                ],
                'restrictions' => [
                    'user.client.contact.index',
                    'user.client.contact.store',
                    'user.client.contact.edit',
                    'user.client.contact.update',
                    'user.client.contact.change.status',
                    'user.client.company.index',
                    'user.client.company.store',
                    'user.client.contact.companies',
                    'user.client.company.edit',
                    'user.client.company.update',
                    'user.client.company.change.status',
                    'user.client.account.index',
                    'user.client.account.store',
                    'user.client.account.edit',
                    'user.client.account.update',
                    'user.client.account.change.status',
                ]
            ],
            'IT Executive' => [
                'routes' => [
                    'user.dashboard',
                    'team.index',
                    'team.store',
                    'team.edit',
                    'team.show',
                    'team.update',
                    'team.change.status',
                    'brand.index',
                    'brand.store',
                    'brand.edit',
                    'brand.update',
                    'brand.change.status',
                    'employee.index',
                    'employee.store',
                    'employee.edit',
                    'employee.update',
                    'employee.change.status',
                    'employee.update.password',
                    'save.settings',
                ],
                'restrictions' => [
                    'user.client.contact.index',
                    'user.client.contact.store',
                    'user.client.contact.edit',
                    'user.client.contact.update',
                    'user.client.contact.change.status',
                    'user.client.company.index',
                    'user.client.company.store',
                    'user.client.contact.companies',
                    'user.client.company.edit',
                    'user.client.company.update',
                    'user.client.company.change.status',
                    'user.client.account.index',
                    'user.client.account.store',
                    'user.client.account.edit',
                    'user.client.account.update',
                    'user.client.account.change.status',
                ]
            ],
            'Accounts' => [
                'routes' => [
                    'user.dashboard',
                    'user.profile',
                    'user.profile.image.update',
                    'user.profile.update',
                    'user.client.contact.index',
                    'user.client.contact.store',
                    'user.client.contact.edit',
                    'user.client.contact.update',
                    'user.client.contact.change.status',
                    'user.client.company.index',
                    'user.client.company.store',
                    'user.client.contact.companies',
                    'user.client.company.edit',
                    'user.client.company.update',
                    'user.client.company.change.status',
                    'user.client.account.index',
                    'user.client.account.store',
                    'user.client.account.edit',
                    'user.client.account.update',
                    'user.client.account.change.status',
                    'user.payment.index',
                    'user.payment.store',
                    'payment-transaction-logs',
                    'save.settings',
                ],
                'restrictions' => [
                ],
            ],
        ],
    ],
];
