name: Mirror

on:
  push:
    branches:
      - main
      - development

jobs:
  mirror-to-repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: ['Trefid-Crm']
    concurrency:
      group: mirror-${{ github.ref }}-${{ matrix.target_repo }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine target branch
        id: target-branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Current branch: $BRANCH_NAME"
          echo "target_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add target repository
        run: |
          git remote add ${{ matrix.target_repo }} https://${{ secrets.MIRRORING_ACCESS_TOKEN }}@github.com/moiz-saviours/${{ matrix.target_repo }}.git

      - name: Verify repository access
        run: |
          curl -s -H "Authorization: token ${{ secrets.MIRRORING_ACCESS_TOKEN }}" \
          https://api.github.com/repos/moiz-saviours/${{ matrix.target_repo }} \
          | jq -r '.name'

      - name: Fetch from target repository
        run: |
          git fetch ${{ matrix.target_repo }} ${{ steps.target-branch.outputs.target_branch }} || echo "Branch might not exist yet"

      - name: Create branch if not exists
        run: |
          if ! git ls-remote --exit-code --heads ${{ matrix.target_repo }} ${{ steps.target-branch.outputs.target_branch }}; then
            git push ${{ matrix.target_repo }} HEAD:refs/heads/${{ steps.target-branch.outputs.target_branch }}
            exit 0
          fi

      - name: Merge changes from target
        run: |
          if git show-ref --verify --quiet refs/remotes/${{ matrix.target_repo }}/${{ steps.target-branch.outputs.target_branch }}; then
            git merge --allow-unrelated-histories ${{ matrix.target_repo }}/${{ steps.target-branch.outputs.target_branch }} -m "Merge from target"
          fi

      - name: Push to target repository
        run: |
          git push ${{ matrix.target_repo }} HEAD:${{ steps.target-branch.outputs.target_branch }} || {
            echo "::error::Push to ${{ matrix.target_repo }} failed"
            exit 1
          }
