name: Mirror (Exclude Self)

on:
  push:
    branches:
      - main
      - development

jobs:
  mirror-to-repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: ['trefid-crm']
    concurrency:
      group: mirror-${{ github.ref }}-${{ matrix.target_repo }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Determine target branch
        id: target-branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "target_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          echo "https://x-access-token:${{ secrets.MIRRORING_ACCESS_TOKEN }}@github.com" > ${HOME}/.git-credentials
          chmod 600 ${HOME}/.git-credentials
          git config --global credential.helper 'store --file=${HOME}/.git-credentials'

      - name: Add target remote
        run: |
          git remote remove ${{ matrix.target_repo }} || true
          git remote add ${{ matrix.target_repo }} https://github.com/moiz-saviours/${{ matrix.target_repo }}.git

      - name: Prepare clean mirror
        run: |
          # Remove the workflow file from staging
          git rm --cached .github/workflows/mirror.yml

          # Commit the removal (but keep file locally)
          git commit -m "Remove mirror workflow from target" || echo "No workflow file to remove"

      - name: Mirror content
        run: |
          # Force push excluding the workflow file
          git push --force ${{ matrix.target_repo }} HEAD:refs/heads/${{ steps.target-branch.outputs.target_branch }}

      - name: Restore local workflow
        run: |
          # Undo the removal commit while keeping the file
          git reset --soft HEAD~1
          git restore --staged .github/workflows/mirror.yml || true
